{
 "title": "rBTC-THETA",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "vault", "query": "rBTC-THETA" }
  ]
 },
 "panels": [
  {
   "title": "TVL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"$vault\"} / 100000000"
    },
    {
     "expr": "crypto_currency{pair=\"btcusd\", exchange=\"kraken\"}"
    }
   ]
  },
  {
   "title": "Until 100M (USD)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"$vault\"} / 100000000"
    },
    {
     "expr": "crypto_currency{pair=\"btcusd\", exchange=\"kraken\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "query_vaults_symbol{job=\"$vault\"}"
    }
   ]
  },
  {
   "title": "Current Option",
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_option{job=\"$vault\"}"
    }
   ]
  },
  {
   "title": "Option Buyer",
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "query_vaultOptionTrades_buyer{job=\"$vault\"}"
    }
   ]
  },
  {
   "title": "Time till Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_expiry{job=\"$vault\"} - time()"
    }
   ]
  },
  {
   "title": "Current Strike Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_strikePrice{job=\"$vault\"} / 100000000"
    }
   ]
  },
  {
   "title": "BTC Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_currency{pair=\"btcusd\", exchange=\"kraken\"}"
    }
   ]
  },
  {
   "title": "Current % to Strike Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(query_vaultShortPositions_strikePrice{job=\"$vault\"} / 100000000)"
    },
    {
     "expr": "(crypto_currency{pair=\"btcusd\", exchange=\"kraken\"})"
    }
   ]
  },
  {
   "title": "Vault Balance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"$vault\"} / 100000000"
    }
   ]
  },
  {
   "title": "Number Depositors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_numDepositors{job=\"$vault\"}"
    }
   ]
  },
  {
   "title": "Price Chart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "crypto_currency{pair=\"btcusd\", exchange=\"kraken\"}",
     "legendFormat": "Current Price"
    },
    {
     "expr": "query_vaultShortPositions_strikePrice{job=\"$vault\"} / 100000000",
     "legendFormat": "Strike Price"
    }
   ]
  },
  {
   "title": "Total Premium Earned",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_totalPremiumEarned{job=\"$vault\"} / 100000000"
    }
   ]
  },
  {
   "title": "Total Vault ROI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(query_vaults_totalPremiumEarned{job=\"$vault\"} / 100000000)",
     "legendFormat": "premium"
    },
    {
     "expr": "query_vaults_totalBalance{job=\"$vault\"}  / 100000000",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Ribbon vs. Deribit Open Interest",
   "type": "graph",
   "description": "Open Interest on Ribbon vs. Deribit on the Current Strike price and Expiry . \n\nNote this takes from the vault total balance and based when funds where added may not reflect the total sold",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deribit_open_interest_compared_to_vault{vault=\"rBTC-THETA\"}",
     "legendFormat": "deribit_open_interest"
    },
    {
     "expr": "query_vaults_totalBalance{job=\"rBTC-THETA\"} / 100000000",
     "legendFormat": "ribbon_open_interest"
    }
   ]
  },
  {
   "title": "Total Withdraw Fee Earned",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_totalWithdrawalFee{job=\"$vault\"} / 1000000000000000000"
    }
   ]
  },
  {
   "title": "Total Vault Loss",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_loss{job=\"rBTC-THETA\"} / 1000000000000000000"
    }
   ]
  }
 ]
}