version: "3.7"
services:
        graphql-exporter:
          #image: quay.io/ricardbejarano/graphql_exporter
            image: lucaskohorst/graphql_exporter
            container_name: graphql-exporter
            hostname: graphql-exporter
            restart: always
            ports: 
                - 9199:9199
            networks:
                - theta-network
            extra_hosts:
                - "host.docker.internal:host-gateway"

        deribit-exporter:
          #image: quay.io/ricardbejarano/graphql_exporter
            build:
                context: ./prometheus
                dockerfile: Dockerfile
            container_name: deribit_exporter    
            hostname: deribit_exporter
            restart: always
            ports: 
                - 9000:9000
            networks:
                - theta-network
            extra_hosts:
                - "host.docker.internal:host-gateway"

        grafana:
            container_name: grafana
            image: grafana/grafana:latest
            restart: unless-stopped
            hostname: grafana
            user: "0"
            volumes:
                - ./grafana/grafana.ini:/etc/grafana/grafana.ini
                - ./grafana/grafanaDatasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
                - ./grafana/grafanaDashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
                - ./grafana/dashboards:/var/lib/grafana/dashboards
                - ./grafana/grafana-storage:/var/lib/grafana
            ports: 
                - 3000:3000
            networks:
                - theta-network
            extra_hosts:
                - "host.docker.internal:host-gateway"

        prometheus:
            container_name: prometheus
            image: prom/prometheus:latest
            user: root # https://github.com/prometheus/prometheus/issues/5976
            restart: unless-stopped
            hostname: prometheus
            command: --storage.tsdb.retention.time=5y --config.file=/etc/prometheus/prometheus.yml
            volumes:
                - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            ports:
                 - 9090:9090
            networks:
                - theta-network
            extra_hosts:
                - "host.docker.internal:host-gateway"

        cryptowat:
            container_name: cryptowat
            image: nbarrientos/cryptowat_exporter
            hostname: cryptowat
            environment: 
                - CRYPTOWAT_PAIRS=ethusd,btcusd
            ports: 
                - 9745:9745
            networks: 
                - theta-network
            extra_hosts:
                - "host.docker.internal:host-gateway"

        db:
            image: mysql:5.7
            container_name: mysql
            hostname: mysql
            restart: always
            environment:
                MYSQL_DATABASE: 'db'
                MYSQL_USER: 'ribbon'
                MYSQL_PASSWORD: 'password'
                MYSQL_ROOT_PASSWORD: 'password'
            ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
            expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
            volumes:
            - my-db:/var/lib/mysql
            extra_hosts:
                - "host.docker.internal:host-gateway"
volumes:
  my-db:
networks:
  theta-network:
    driver: bridge
