version: "3.7"
services:
        graphql-exporter:
          #image: quay.io/ricardbejarano/graphql_exporter
            image: lucaskohorst/graphql_exporter
            container_name: graphql-exporter
            hostname: graphql-exporter
            restart: always
            ports: 
                - 9199:9199
            networks:
                - theta-network

        grafana:
            container_name: grafana
            image: grafana/grafana:latest
            restart: unless-stopped
            hostname: grafana
            user: "0"
            volumes:
                - ./grafana/grafana.ini:/etc/grafana/grafana.ini
                - ./grafana/grafanaDatasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
                - ./grafana/grafanaDashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
                - ./grafana/dashboards:/var/lib/grafana/dashboards
                - ./grafana/grafana-storage:/var/lib/grafana
            ports: 
                - 3000:3000
            networks:
                - theta-network

        prometheus:
            container_name: prometheus
            image: prom/prometheus:latest
            user: root # https://github.com/prometheus/prometheus/issues/5976
            restart: unless-stopped
            hostname: prometheus
            command: --storage.tsdb.retention.time=7d --config.file=/etc/prometheus/prometheus.yml
            volumes:
                - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            ports:
                 - 9090:9090
            networks:
                - theta-network

        cryptowat:
            container_name: cryptowat
            image: nbarrientos/cryptowat_exporter
            hostname: cryptowat
            environment: 
                - CRYPTOWAT_PAIRS=ethusd
            ports: 
                - 9745:9745
            networks: 
                - theta-network

networks:
  theta-network:
    driver: bridge
