scrape_configs:
  - job_name: "theta-vaults"
    metrics_path: "/query"
    params:
      endpoint:
        ["https://api.thegraph.com/subgraphs/name/kenchangh/ribbon-finance"]
      query:
        - |
          {
            vaults(first: 1) {
              id
              name
              symbol
              totalPremiumEarned
              totalWithdrawalFee
              numDepositors
            }
            vaultShortPositions(first:1, orderBy:expiry, orderDirection:desc){
              strikePrice
              option
              strikePrice
              openedAt
              closedAt
              premiumEarned
              openTxhash
              closeTxhash
              expiry
            }
          }
    static_configs:
      - targets: ["172.22.0.2:9199"] # graphql_exporter address:port

