scrape_configs:
  - job_name: cryptowat
    static_configs:
      - targets: ['cryptowat:9745']

  - job_name: "theta-vaults"
    metrics_path: "/query"
    params:
      endpoint:
        ["https://api.thegraph.com/subgraphs/name/kenchangh/ribbon-finance"]
      query:
        - |
          {
            vaults(first: 1) {
              id
              name
              symbol
              totalPremiumEarned
              totalWithdrawalFee
              numDepositors
            }
            vaultShortPositions(first:1, orderBy:expiry, orderDirection:desc){
              strikePrice
              option
              strikePrice
              openedAt
              closedAt
              premiumEarned
              openTxhash
              closeTxhash
              expiry
            }
            balanceUpdates(first:1){
              balance
              yieldEarned
            }
            vaultOptionTrades{
              premium
              sellAmount
              buyer
              optionToken
            }
            instrumentPositions {
              id
              instrumentAddress
              account
              cost
              exercised
              amount
              optionTypes
              strikePrices
              venues
              expiry
              exerciseProfit
            }
          }
    static_configs:
      - targets: ["graphql-exporter:9199"] # graphql_exporter address:port

