{
 "title": "Options Sold",
 "time": { "from": "now/y", "to": "now" },
 "panels": [
  {
   "title": "Contract Volume Per Week",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  name AS metric,\n  sum(sellAmount / 100000000) AS sellAmount\nFROM options\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Options Sold (rETH-THETA)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT\n  name, timestamp, optionToken, txhash, premium / 1000000000000000000 as premium, sellAmount / 100000000 as sellAmount\nFROM options where name = \"Ribbon ETH Theta Vault\" order by timestamp DESC"
    }
   ]
  },
  {
   "title": "Options Sold (rBTC-THETA)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT\n  name, timestamp, optionToken, txhash, premium / 100000000 as premium, sellAmount / 100000000 as sellAmount\nFROM options where name = \"Ribbon BTC Theta Vault\" order by timestamp DESC"
    }
   ]
  },
  {
   "title": "Options Sold (T-USDC-P-ETH)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT\n  name, timestamp, optionToken, txhash, premium / 1000000 as premium, sellAmount / 100000000 as sellAmount\nFROM options where name = \"Ribbon USDC Theta Vault ETH Put\" order by timestamp DESC"
    }
   ]
  }
 ]
}