{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "# Ribbon Vault Metrics\n- [ribbon.finance](https://ribbon.finance)\n- [Twitter](https://twitter.com/ribbonfinance)\n- [Discord](https://discord.com/invite/85gcVafPyN)\n- [Metrics](https://github.com/Lucas-Kohorst/theta-vault-metrics)\n\n### Development \nThe metrics are gathered from the [Ribbon Subgraph](https://thegraph.com/explorer/subgraph/kenchangh/ribbon-finance?query=Example%20query) and then scraped via a [graphql-exporter](https://github.com/ricardbejarano/graphql_exporter). ETH price feeds are also pulled in via [cryptowat-exporter](https://github.com/nbarrientos/cryptowat_exporter).\n\nEverything is scraped via [prometheus](https://prometheus.io/) and displayed in [grafana](https://grafana.com/)"
   }
  },
  { "type": "dashlist", "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 } },
  {
   "title": "TVL (USD)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"rETH-THETA\"}  / 1000000000000000000",
     "legendFormat": "reth_theta"
    },
    {
     "expr": "crypto_currency{pair=\"ethusd\", exchange=\"kraken\"}",
     "legendFormat": "eth"
    },
    {
     "expr": "query_vaults_totalBalance{job=\"rBTC-THETA\"}  / 100000000",
     "legendFormat": "rbtc-theta"
    },
    {
     "expr": "crypto_currency{pair=\"btcusd\", exchange=\"kraken\"}",
     "legendFormat": "btc"
    },
    {
     "expr": "query_vaults_totalBalance{job=\"rUSDC-ETH-P-THETA\"}  / 1000000",
     "legendFormat": "rUSDC-ETH-P-THETA"
    },
    {
     "expr": "query_vaults_totalBalance{job=\"ryvUSDC-ETH-P-THETA\"}  / 1000000",
     "legendFormat": "ryvUSDC-ETH-P-THETA"
    }
   ]
  },
  {
   "title": "rBTC-THETA TVL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"rBTC-THETA\"} / 100000000"
    },
    {
     "expr": "crypto_currency{pair=\"btcusd\", exchange=\"kraken\"}"
    }
   ]
  },
  {
   "title": "rETH-THETA TVL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"rETH-THETA\"}  / 1000000000000000000"
    },
    {
     "expr": "crypto_currency{pair=\"ethusd\", exchange=\"kraken\"}"
    }
   ]
  },
  {
   "title": "rUSDC-ETH-P-THETA TVL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"rUSDC-ETH-P-THETA\"} / 1000000",
     "legendFormat": "tvl"
    }
   ]
  },
  {
   "title": "ryvUSDC-ETH-P-THETA TVL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"ryvUSDC-ETH-P-THETA\"} / 1000000",
     "legendFormat": "tvl"
    }
   ]
  }
 ]
}