{
 "title": "Overview Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TVL (USD)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"rETH-THETA\"}  / 1000000000000000000",
     "legendFormat": "reth_theta"
    },
    {
     "expr": "crypto_currency{pair=\"ethusd\", exchange=\"kraken\"}",
     "legendFormat": "eth"
    },
    {
     "expr": "query_vaults_totalBalance{job=\"rBTC-THETA\"}  / 100000000",
     "legendFormat": "rbtc-theta"
    },
    {
     "expr": "crypto_currency{pair=\"btcusd\", exchange=\"kraken\"}",
     "legendFormat": "btc"
    }
   ]
  },
  {
   "title": "TVL (BTC)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"rBTC-THETA\"} / 100000000"
    }
   ]
  },
  {
   "title": "TVL (ETH)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"rETH-THETA\"} / 1000000000000000000"
    }
   ]
  },
  {
   "title": "rBTC-THETA TVL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"rBTC-THETA\"} / 100000000"
    },
    {
     "expr": "crypto_currency{pair=\"btcusd\", exchange=\"kraken\"}"
    }
   ]
  },
  {
   "title": "rETH-THETA TVL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"rETH-THETA\"}  / 1000000000000000000"
    },
    {
     "expr": "crypto_currency{pair=\"ethusd\", exchange=\"kraken\"}"
    }
   ]
  },
  {
   "title": "rBTC-THETA Number Depositors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_numDepositors{job=\"rBTC-THETA\"}"
    }
   ]
  },
  {
   "title": "rETH-THETA Number Depositors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_numDepositors{job=\"rETH-THETA\"}"
    }
   ]
  }
 ]
}