{
 "title": "rBTC-THETA",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "vault", "query": "rBTC-THETA" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "# Theta Vault Metrics\n- [ribbon.finance](https://ribbon.finance)\n- [Twitter](https://twitter.com/ribbonfinance)\n- [Discord](https://discord.com/invite/85gcVafPyN)\n- [Metrics](https://github.com/Lucas-Kohorst/theta-vault-metrics)\n\n### Overview\n[ribbon.finance](https://ribbon.finance) provides sustainable alpha for everyone. The primary product is the [theta vault](https://app.ribbon.finance/theta-vault/T-100-E) which earns yield by selling far out of the money covered calls. \n\nYou can find metrics for the vault at [metrics.thetagang.info](http://metrics.thetagang.info/d/hH2ap5XGz/theta-vault?orgId=1)\n\n### Development \nThe metrics are gathered from the [Ribbon Subgraph](https://thegraph.com/explorer/subgraph/kenchangh/ribbon-finance?query=Example%20query) and then scraped via a [graphql-exporter](https://github.com/ricardbejarano/graphql_exporter). ETH price feeds are also pulled in via [cryptowat-exporter](https://github.com/nbarrientos/cryptowat_exporter).\n\nEverything is scraped via [prometheus](https://prometheus.io/) and displayed in [grafana](https://grafana.com/)"
   }
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "query_vaults_symbol{job=\"$vault\"}"
    }
   ]
  },
  {
   "title": "Current Option",
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_option{job=\"$vault\"}"
    }
   ]
  },
  {
   "title": "Option Buyer",
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "query_vaultOptionTrades_buyer{job=\"$vault\"}"
    }
   ]
  },
  {
   "title": "Time till Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_expiry{job=\"$vault\"} - time()"
    }
   ]
  },
  {
   "title": "Current Strike Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_strikePrice{job=\"$vault\"} / 100000000"
    }
   ]
  },
  {
   "title": "BTC Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_currency{pair=\"btcusd\", exchange=\"kraken\"}"
    }
   ]
  },
  {
   "title": "Current % to Strike Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(query_vaultShortPositions_strikePrice{job=\"$vault\"} / 100000000)"
    },
    {
     "expr": "(crypto_currency{pair=\"btcusd\", exchange=\"kraken\"})"
    }
   ]
  },
  {
   "title": "TVL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"$vault\"} / 100000000"
    },
    {
     "expr": "crypto_currency{pair=\"btcusd\", exchange=\"kraken\"}"
    }
   ]
  },
  {
   "title": "Until 100M (USD)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"$vault\"} / 100000000"
    },
    {
     "expr": "crypto_currency{pair=\"btcusd\", exchange=\"kraken\"}"
    }
   ]
  },
  {
   "title": "Price Chart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "crypto_currency{pair=\"btcusd\", exchange=\"kraken\"}",
     "legendFormat": "Current Price"
    },
    {
     "expr": "query_vaultShortPositions_strikePrice{job=\"$vault\"} / 100000000",
     "legendFormat": "Strike Price"
    }
   ]
  },
  {
   "title": "Vault Balance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_totalBalance{job=\"$vault\"} / 100000000"
    }
   ]
  },
  {
   "title": "Number Depositors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_numDepositors{job=\"$vault\"}"
    }
   ]
  },
  {
   "title": "Total Premium Earned",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_totalPremiumEarned{job=\"$vault\"} / 100000000"
    }
   ]
  },
  {
   "title": "Total Vault ROI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(query_vaults_totalPremiumEarned{job=\"$vault\"} / 100000000)",
     "legendFormat": "premium"
    },
    {
     "expr": "query_vaults_totalBalance{job=\"$vault\"}  / 100000000",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Total Withdraw Fee Earned",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaults_totalWithdrawalFee{job=\"$vault\"} / 1000000000000000000"
    }
   ]
  }
 ]
}