{
 "title": "Ribbon vs. Deribit",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "query_vaults_symbol{job=\"rBTC-THETA\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "query_vaults_symbol{job=\"rETH-THETA\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "query_vaults_symbol{job=\"rUSDC-ETH-P-THETA\"}"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
   "options": {
    "content": "[This vault](https://app.ribbon.finance/theta-vault/T-WBTC-C) earns yield on its WBTC deposits by running an automated WBTC covered call strategy."
   }
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 2 },
   "options": {
    "content": "[This vault](https://app.ribbon.finance/theta-vault/T-ETH-C) earns yield on its ETH deposits by running an automated ETH covered call strategy."
   }
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
   "options": {
    "content": "[This vault](https://app.ribbon.finance/theta-vault/T-USDC-P-ETH) earns yield on its USDC deposits by running an automated strategy that sells ETH put options. The idea is to profit when the asset goes up in price"
   }
  },
  {
   "title": "Current Strike Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_strikePrice{job=\"rBTC-THETA\"} / 100000000"
    }
   ]
  },
  {
   "title": "Current % to Strike Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(query_vaultShortPositions_strikePrice{job=\"rBTC-THETA\"} / 100000000)"
    },
    {
     "expr": "(crypto_currency{pair=\"btcusd\", exchange=\"kraken\"})"
    }
   ]
  },
  {
   "title": "Current Strike Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_strikePrice{job=\"rETH-THETA\"} / 100000000"
    }
   ]
  },
  {
   "title": "Current % to Strike Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(query_vaultShortPositions_strikePrice{job=\"rETH-THETA\"} / 100000000)"
    },
    {
     "expr": "(crypto_currency{pair=\"ethusd\", exchange=\"kraken\"})"
    }
   ]
  },
  {
   "title": "Current Strike Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_strikePrice{job=\"rUSDC-ETH-P-THETA\"} / 100000000"
    }
   ]
  },
  {
   "title": "Current % to Strike Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(query_vaultShortPositions_strikePrice{job=\"rUSDC-ETH-P-THETA\"} / 100000000)"
    },
    {
     "expr": "(crypto_currency{pair=\"ethusd\", exchange=\"kraken\"})"
    }
   ]
  },
  {
   "title": "Ribbon vs. Deribit Open Interest",
   "type": "piechart",
   "description": "Open Interest on Ribbon vs. Deribit on the Current Strike price and Expiry . \n\nNote this takes from the vault total balance and based when funds where added may not reflect the total sold",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deribit_open_interest_compared_to_vault{vault=\"rBTC-THETA\"}",
     "legendFormat": "BTC Covered Call (Deribit)"
    },
    {
     "expr": "query_vaults_totalBalance{job=\"rBTC-THETA\"} / 100000000",
     "legendFormat": "BTC Covered Call (Ribbon)"
    }
   ]
  },
  {
   "title": "Ribbon vs. Deribit Open Interest",
   "type": "piechart",
   "description": "Open Interest on Ribbon vs. Deribit on the Current Strike price and Expiry . \n\nNote this takes from the vault total balance and based when funds where added may not reflect the total sold",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deribit_open_interest_compared_to_vault{vault=\"rETH-THETA\"}",
     "legendFormat": "ETH Covered Call (Deribit)"
    },
    {
     "expr": "query_vaults_totalBalance{job=\"rETH-THETA\"} / 1000000000000000000",
     "legendFormat": "ETH Covered Call (Ribbon)"
    }
   ]
  },
  {
   "title": "Ribbon vs. Deribit Open Interest",
   "type": "piechart",
   "description": "Open Interest on Ribbon vs. Deribit on the Current Strike price and Expiry . \n\nNote this takes from the vault total balance and based when funds where added may not reflect the total sold",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deribit_open_interest_compared_to_vault{vault=\"rUSDC-ETH-P-THETA\"}",
     "legendFormat": "ETH Protected Put (Deribit)"
    },
    {
     "expr": "query_vaults_totalBalance{job=\"rUSDC-ETH-P-THETA\"} / 1000000000",
     "legendFormat": "ETH Protected Put (Ribbon)"
    }
   ]
  }
 ]
}