apiVersion: 1
deleteDatasources: []
datasources:
  - name: Prometheus
    access: proxy
    isDefault: true
    type: prometheus
    url: http://prometheus:9090/
  - name: mysql
    type: mysql
    url: host.docker.internal:3306
    database: ribbon
    user: ribbon
    secureJsonData:
      password: password
