{
 "title": "Theta Vault",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "query_vaults_name" }
   ]
  },
  {
   "title": "Number Depositors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "query_vaults_numDepositors" }
   ]
  },
  {
   "title": "Total Premium Earned",
   "type": "table",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "query_vaults_totalPremiumEarned"
    }
   ]
  },
  {
   "title": "ETH Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_currency{pair=\"ethusd\", exchange=\"coinbase-pro\"}"
    }
   ]
  },
  {
   "title": "Percent to Strike",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_strikePrice"
    },
    {
     "expr": "crypto_currency{pair=\"ethusd\", exchange=\"coinbase-pro\"}"
    }
   ]
  },
  {
   "title": "Vault Balance",
   "type": "table",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    { "expr": "query_balanceUpdates_balance" }
   ]
  },
  {
   "title": "Total Withdraw Fee Earned",
   "type": "table",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "query_vaults_totalWithdrawalFee"
    }
   ]
  },
  {
   "title": "Yield Earned",
   "type": "table",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "query_balanceUpdates_yieldEarned"
    }
   ]
  },
  {
   "title": "Total Withdraw Fee Earned",
   "type": "table",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "query_vaults_totalWithdrawalFee"
    }
   ]
  },
  {
   "title": "Current Option",
   "type": "table",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_option"
    }
   ]
  },
  {
   "title": "Current Option Open Open Tx",
   "type": "table",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_openTxhash"
    }
   ]
  },
  {
   "title": "Opened",
   "type": "table",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_openedAt"
    },
    {}
   ]
  },
  {
   "title": "Strike Price",
   "type": "table",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "query_vaultShortPositions_strikePrice"
    }
   ]
  },
  {
   "title": "Option Expiry",
   "type": "table",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(query_vaultShortPositions_expiry) by (value)"
    },
    {}
   ]
  }
 ]
}